version: '3.8'

services:
  meilisearch:
    image: getmeili/meilisearch:v1.14.0
    ports:
      - "7700:7700"
    environment:
      MEILI_NO_ANALYTICS: true
      MEILI_MASTER_KEY: "masterKey"
  web:
    # Build the image from the Dockerfile in the current directory
    build: .

    # Host the FastAPI application on port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - .venv/
    depends_on:
      - meilisearch